import { useRef } from 'react';
import { useGSAP } from '@gsap/react';
import gsap from 'gsap';

export function Windows() {
  const groupRef = useRef<SVGGElement[]>([]);

  useGSAP(() => {
    const tl = gsap.timeline({
      repeat: -1,
      yoyo: true,
      defaults: { ease: 'power1.inOut', duration: 1 },
    });

    groupRef.current.reverse().forEach((group, index) => {
      tl.to(
        group,
        {
          yPercent() {
            if (index === 0) return -2;
            return index * -12;
          },
          xPercent() {
            if (index === 0) return 2;
            return index * 12;
          },
          duration: 1,
          ease: 'power2.inOut',
        },
        '<'
      );
    });
  }, []);

  return (
    <svg
      viewBox="0 0 774 469"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className="overflow-visible"
    >
      <g
        ref={(el) => {
          if (el && !groupRef.current.includes(el)) {
            groupRef.current.push(el);
          }
        }}
      >
        <rect
          x="2"
          y="2"
          width="770"
          height="465"
          fill="var(--accent)"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <circle cx="56" cy="36" r="10" fill="var(--background)" />
        <circle
          cx="92"
          cy="36"
          r="9"
          stroke="var(--background)"
          strokeWidth="2"
        />
        <circle
          cx="128"
          cy="36"
          r="9"
          stroke="var(--background)"
          strokeWidth="2"
        />
        <line
          x1="46"
          y1="82"
          x2="434"
          y2="82"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="91"
          y1="112"
          x2="388"
          y2="112"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="126"
          y1="142"
          x2="620"
          y2="142"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="91"
          y1="172"
          x2="388"
          y2="172"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46.0185"
          y1="202"
          x2="153.019"
          y2="202.991"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="263"
          x2="114"
          y2="263"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="292.991"
          x2="307"
          y2="292.991"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="352.991"
          x2="288"
          y2="352.991"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="383"
          x2="307"
          y2="383"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="413"
          x2="288"
          y2="413"
          stroke="var(--background)"
          strokeWidth="4"
        />
      </g>
      <g
        ref={(el) => {
          if (el && !groupRef.current.includes(el)) {
            groupRef.current.push(el);
          }
        }}
      >
        <rect
          x="2"
          y="2"
          width="770"
          height="465"
          fill="var(--accent)"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <circle cx="56" cy="36" r="10" fill="var(--background)" />
        <circle
          cx="92"
          cy="36"
          r="9"
          stroke="var(--background)"
          strokeWidth="2"
        />
        <circle
          cx="128"
          cy="36"
          r="9"
          stroke="var(--background)"
          strokeWidth="2"
        />
        <line
          x1="46"
          y1="82"
          x2="434"
          y2="82"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="91"
          y1="112"
          x2="388"
          y2="112"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="126"
          y1="142"
          x2="620"
          y2="142"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="91"
          y1="172"
          x2="388"
          y2="172"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46.0185"
          y1="202"
          x2="153.019"
          y2="202.991"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="263"
          x2="114"
          y2="263"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="292.991"
          x2="307"
          y2="292.991"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="352.991"
          x2="288"
          y2="352.991"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="383"
          x2="307"
          y2="383"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="413"
          x2="288"
          y2="413"
          stroke="var(--background)"
          strokeWidth="4"
        />
      </g>
      <g
        ref={(el) => {
          if (el && !groupRef.current.includes(el)) {
            groupRef.current.push(el);
          }
        }}
      >
        <rect
          x="2"
          y="2"
          width="770"
          height="465"
          fill="var(--accent)"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <circle cx="56" cy="36" r="10" fill="var(--background)" />
        <circle
          cx="92"
          cy="36"
          r="9"
          stroke="var(--background)"
          strokeWidth="2"
        />
        <circle
          cx="128"
          cy="36"
          r="9"
          stroke="var(--background)"
          strokeWidth="2"
        />
        <line
          x1="46"
          y1="82"
          x2="434"
          y2="82"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="91"
          y1="112"
          x2="388"
          y2="112"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="126"
          y1="142"
          x2="620"
          y2="142"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="91"
          y1="172"
          x2="388"
          y2="172"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46.0185"
          y1="202"
          x2="153.019"
          y2="202.991"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="263"
          x2="114"
          y2="263"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="292.991"
          x2="307"
          y2="292.991"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="352.991"
          x2="288"
          y2="352.991"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="383"
          x2="307"
          y2="383"
          stroke="var(--background)"
          strokeWidth="4"
        />
        <line
          x1="46"
          y1="413"
          x2="288"
          y2="413"
          stroke="var(--background)"
          strokeWidth="4"
        />
      </g>
    </svg>
  );
}
